//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENSES
    {
        public decimal ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal USERS_ID { get; set; }
        public decimal CATEGORY_ID { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
